# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proper.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1092, 948)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 850))
        MainWindow.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(20, 5, 0, 5)
        self.gridLayout_2.setHorizontalSpacing(25)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Pirrbtn = QtWidgets.QRadioButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Pirrbtn.setFont(font)
        self.Pirrbtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"")

        self.Pirrbtn.setObjectName("Pirrbtn")
        self.gridLayout_2.addWidget(self.Pirrbtn, 0, 0, 1, 1)
        self.Kararbtn = QtWidgets.QRadioButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Kararbtn.setFont(font)
        self.Kararbtn.setStyleSheet("color: rgb(255, 255, 255);")

        self.Kararbtn.setObjectName("Kararbtn")
        self.gridLayout_2.addWidget(self.Kararbtn, 0, 2, 1, 1)
        self.Ghrbtn = QtWidgets.QRadioButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Ghrbtn.setFont(font)
        self.Ghrbtn.setStyleSheet("color: rgb(255, 255, 255);")

        self.Ghrbtn.setObjectName("Ghrbtn")
        self.gridLayout_2.addWidget(self.Ghrbtn, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_2, 2, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setMidLineWidth(-1)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(150, 150))
        self.label_12.setMaximumSize(QtCore.QSize(150, 150))
        self.label_12.setStyleSheet("QLabel{\n"
"border:2px solid;\n"
"\n"
"}")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/iitblogo/iitblogo.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 20pt \"Arial\";")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setMinimumSize(QtCore.QSize(150, 0))
        self.label_14.setMaximumSize(QtCore.QSize(150, 150))
        self.label_14.setStyleSheet("QLabel{\n"
"border:2px solid\n"
"}")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/iitblogo/DRDO-logo.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("\n"
"font: 87 12pt \"Arial Black\";")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"border:2px solid;\n"
"border-color: rgb(80, 80, 80);\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid;\n"
"border-color: white;\n"
"\n"
"}")
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.upload_4 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload_4.sizePolicy().hasHeightForWidth())
        self.upload_4.setSizePolicy(sizePolicy)
        self.upload_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.upload_4.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 75 12pt \"Arial\";\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: 2px ;\n"
"    border-radius: 4px;\n"
" \n"
"}\n"
"QPushButton:hover {\n"
"  background-color:#b3b3b3;\n"
"  color: black;\n"
"}\n"
"\n"
"")
        self.upload_4.setObjectName("upload_4")
        self.horizontalLayout_4.addWidget(self.upload_4)
        self.label_9 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_9.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_9.sizePolicy().hasHeightForWidth())
        self.lineEdit_9.setSizePolicy(sizePolicy)
        self.lineEdit_9.setStyleSheet("QLineEdit{\n"
"border:2px solid;\n"
"border-color: rgb(80, 80, 80);\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid;\n"
"border-color: white;\n"
"\n"
"}")
        self.lineEdit_9.setClearButtonEnabled(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_4.addWidget(self.lineEdit_9)
        self.upload_9 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload_9.sizePolicy().hasHeightForWidth())
        self.upload_9.setSizePolicy(sizePolicy)
        self.upload_9.setMaximumSize(QtCore.QSize(16777215, 30))
        self.upload_9.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 75 12pt \"Arial\";\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: 2px ;\n"
"    border-radius: 4px;\n"
" \n"
"}\n"
"QPushButton:hover {\n"
"  background-color:#b3b3b3;\n"
"  color: black;\n"
"}\n"
"\n"
"")
        self.upload_9.setObjectName("upload_9")
        self.horizontalLayout_4.addWidget(self.upload_9)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 5)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(3, 2)
        self.horizontalLayout_4.setStretch(4, 5)
        self.horizontalLayout_4.setStretch(5, 1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setStyleSheet("QLineEdit{\n"
"border:2px solid;\n"
"border-color: rgb(80, 80, 80);\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid;\n"
"border-color: white;\n"
"\n"
"}")
        self.lineEdit_5.setClearButtonEnabled(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_5.addWidget(self.lineEdit_5)
        self.upload_5 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload_5.sizePolicy().hasHeightForWidth())
        self.upload_5.setSizePolicy(sizePolicy)
        self.upload_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.upload_5.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 75 12pt \"Arial\";\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: 2px ;\n"
"    border-radius: 4px;\n"
" \n"
"}\n"
"QPushButton:hover {\n"
"  background-color:#b3b3b3;\n"
"  color: black;\n"
"}\n"
"\n"
"")
        self.upload_5.setObjectName("upload_5")
        self.horizontalLayout_5.addWidget(self.upload_5)
        self.label_5 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_10.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_10.sizePolicy().hasHeightForWidth())
        self.lineEdit_10.setSizePolicy(sizePolicy)
        self.lineEdit_10.setStyleSheet("QLineEdit{\n"
"border:2px solid;\n"
"border-color: rgb(80, 80, 80);\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid;\n"
"border-color: white;\n"
"\n"
"}")
        self.lineEdit_10.setClearButtonEnabled(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_5.addWidget(self.lineEdit_10)
        self.upload_10 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload_10.sizePolicy().hasHeightForWidth())
        self.upload_10.setSizePolicy(sizePolicy)
        self.upload_10.setMaximumSize(QtCore.QSize(16777215, 30))
        self.upload_10.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 75 12pt \"Arial\";\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: 2px ;\n"
"    border-radius: 4px;\n"
" \n"
"}\n"
"QPushButton:hover {\n"
"  background-color:#b3b3b3;\n"
"  color: black;\n"
"}\n"
"")
        self.upload_10.setObjectName("upload_10")
        self.horizontalLayout_5.addWidget(self.upload_10)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 5)
        self.horizontalLayout_5.setStretch(2, 1)
        self.horizontalLayout_5.setStretch(3, 2)
        self.horizontalLayout_5.setStretch(4, 5)
        self.horizontalLayout_5.setStretch(5, 1)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, -1, 0, -1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEdit_1 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_1.sizePolicy().hasHeightForWidth())
        self.lineEdit_1.setSizePolicy(sizePolicy)
        self.lineEdit_1.setStyleSheet("QLineEdit{\n"
"border:2px solid;\n"
"border-color: rgb(80, 80, 80);\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid;\n"
"border-color: white;\n"
"\n"
"}")
        self.lineEdit_1.setClearButtonEnabled(True)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.horizontalLayout.addWidget(self.lineEdit_1)
        self.upload_1 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload_1.sizePolicy().hasHeightForWidth())
        self.upload_1.setSizePolicy(sizePolicy)
        self.upload_1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.upload_1.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 75 12pt \"Arial\";\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: 2px ;\n"
"    border-radius: 4px;\n"
" \n"
"}\n"
"QPushButton:hover {\n"
"  background-color:#b3b3b3;\n"
"  color: black;\n"
"}\n"
"\n"
"\n"
"")
        self.upload_1.setObjectName("upload_1")
        self.horizontalLayout.addWidget(self.upload_1)
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setStyleSheet("QLineEdit{\n"
"border:2px solid;\n"
"border-color: rgb(80, 80, 80);\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid;\n"
"border-color: white;\n"
"\n"
"}")
        self.lineEdit_6.setClearButtonEnabled(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout.addWidget(self.lineEdit_6)
        self.upload_6 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload_6.sizePolicy().hasHeightForWidth())
        self.upload_6.setSizePolicy(sizePolicy)
        self.upload_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.upload_6.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 75 12pt \"Arial\";\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: 2px ;\n"
"    border-radius: 4px;\n"
" \n"
"}\n"
"QPushButton:hover {\n"
"  background-color:#b3b3b3;\n"
"  color: black;\n"
"}\n"
"\n"
"")
        self.upload_6.setIconSize(QtCore.QSize(25, 25))
        self.upload_6.setObjectName("upload_6")
        self.horizontalLayout.addWidget(self.upload_6)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 2)
        self.horizontalLayout.setStretch(4, 5)
        self.horizontalLayout.setStretch(5, 1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"border:2px solid;\n"
"border-color: rgb(80, 80, 80);\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid;\n"
"border-color: white;\n"
"\n"
"}\n"
"")
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.upload_2 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload_2.sizePolicy().hasHeightForWidth())
        self.upload_2.setSizePolicy(sizePolicy)
        self.upload_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.upload_2.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 75 12pt \"Arial\";\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: 2px ;\n"
"    border-radius: 4px;\n"
" \n"
"}\n"
"QPushButton:hover {\n"
"  background-color:#b3b3b3;\n"
"  color: black;\n"
"}\n"
"\n"
"")
        self.upload_2.setObjectName("upload_2")
        self.horizontalLayout_2.addWidget(self.upload_2)
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_7.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setStyleSheet("QLineEdit{\n"
"border:2px solid;\n"
"border-color: rgb(80, 80, 80);\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid;\n"
"border-color: white;\n"
"\n"
"}")
        self.lineEdit_7.setClearButtonEnabled(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_2.addWidget(self.lineEdit_7)
        self.upload_7 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload_7.sizePolicy().hasHeightForWidth())
        self.upload_7.setSizePolicy(sizePolicy)
        self.upload_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.upload_7.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 75 12pt \"Arial\";\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: 2px ;\n"
"    border-radius: 4px;\n"
" \n"
"}\n"
"QPushButton:hover {\n"
"  background-color:#b3b3b3;\n"
"  color: black;\n"
"}\n"
"\n"
"")
        self.upload_7.setObjectName("upload_7")
        self.horizontalLayout_2.addWidget(self.upload_7)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 5)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 2)
        self.horizontalLayout_2.setStretch(4, 5)
        self.horizontalLayout_2.setStretch(5, 1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(5, -1, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"border:2px solid;\n"
"border-color: rgb(80, 80, 80);\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid;\n"
"border-color: white;\n"
"\n"
"}")
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.upload_3 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload_3.sizePolicy().hasHeightForWidth())
        self.upload_3.setSizePolicy(sizePolicy)
        self.upload_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.upload_3.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 75 12pt \"Arial\";\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: 2px ;\n"
"    border-radius: 4px;\n"
" \n"
"}\n"
"QPushButton:hover {\n"
"  background-color:#b3b3b3;\n"
"  color: black;\n"
"}\n"
"\n"
"")
        self.upload_3.setObjectName("upload_3")
        self.horizontalLayout_3.addWidget(self.upload_3)
        self.label_8 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_8.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        self.lineEdit_8.setStyleSheet("QLineEdit{\n"
"border:2px solid;\n"
"border-color: rgb(80, 80, 80);\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid;\n"
"border-color: white;\n"
"\n"
"}")
        self.lineEdit_8.setClearButtonEnabled(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_3.addWidget(self.lineEdit_8)
        self.upload_8 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload_8.sizePolicy().hasHeightForWidth())
        self.upload_8.setSizePolicy(sizePolicy)
        self.upload_8.setMaximumSize(QtCore.QSize(16777215, 30))
        self.upload_8.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 75 12pt \"Arial\";\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: 2px ;\n"
"    border-radius: 4px;\n"
" \n"
"}\n"
"QPushButton:hover {\n"
"  background-color:#b3b3b3;\n"
"  color: black;\n"
"}\n"
"\n"
"")
        self.upload_8.setObjectName("upload_8")
        self.horizontalLayout_3.addWidget(self.upload_8)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 5)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 2)
        self.horizontalLayout_3.setStretch(4, 5)
        self.horizontalLayout_3.setStretch(5, 1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 4, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(self.frame_3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(41)
        self.splitter.setObjectName("splitter")
        self.submitbtn = QtWidgets.QPushButton(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submitbtn.sizePolicy().hasHeightForWidth())
        self.submitbtn.setSizePolicy(sizePolicy)
        self.submitbtn.setMaximumSize(QtCore.QSize(200, 50))
        self.submitbtn.setStyleSheet("QPushButton{\n"
"  background-color: #4CAF50; /* Green */\n"
"  border: none;\n"
"  color: white;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  font-size: 16px;\n"
"  transition-duration: 0.4s;\n"
"}\n"
"\n"
"QPushButton {\n"
"  background-color: white; \n"
"  color: black; \n"
"  border: 2px solid #4CAF50;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #4CAF50;\n"
"  color: white;\n"
"}\n"
"\n"
"\n"
"")
        self.submitbtn.setObjectName("submitbtn")
        self.clearbtn = QtWidgets.QPushButton(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearbtn.sizePolicy().hasHeightForWidth())
        self.clearbtn.setSizePolicy(sizePolicy)
        self.clearbtn.setMaximumSize(QtCore.QSize(200, 50))
        self.clearbtn.setStyleSheet("QPushButton{\n"
"  background-color: #4CAF50; /* Green */\n"
"  border: none;\n"
"  color: white;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  font-size: 16px;\n"
"  transition-duration: 0.4s;\n"
"}\n"
"QPushButton {\n"
"  background-color: white; \n"
"  color: black; \n"
"  border: 2px solid #008CBA;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #008CBA;\n"
"  color: white;\n"
"}")
        self.clearbtn.setObjectName("clearbtn")
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_3, 5, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setMidLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Pirrbtn.setText(_translate("MainWindow", "Pirpanjal"))
        self.Kararbtn.setText(_translate("MainWindow", "Karakoram"))
        self.Ghrbtn.setText(_translate("MainWindow", "Greater Himalaya"))
        self.label_13.setText(_translate("MainWindow", "Snow Depth Model"))
        self.label_4.setText(_translate("MainWindow", "SCD"))
        self.upload_4.setText(_translate("MainWindow", "Upload"))
        self.label_9.setText(_translate("MainWindow", "BT89V"))
        self.upload_9.setText(_translate("MainWindow", "Upload"))
        self.label_10.setText(_translate("MainWindow", "BT10H"))
        self.upload_5.setText(_translate("MainWindow", "Upload"))
        self.label_5.setText(_translate("MainWindow", "BT36V"))
        self.upload_10.setText(_translate("MainWindow", "Upload"))
        self.label_6.setText(_translate("MainWindow", "Elevation"))
        self.upload_1.setText(_translate("MainWindow", "Upload"))
        self.label.setText(_translate("MainWindow", "BT18H"))
        self.upload_6.setText(_translate("MainWindow", "Upload"))
        self.label_7.setText(_translate("MainWindow", "Slope       "))
        self.upload_2.setText(_translate("MainWindow", "Upload"))
        self.label_2.setText(_translate("MainWindow", "BT23H"))
        self.upload_7.setText(_translate("MainWindow", "Upload"))
        self.label_3.setText(_translate("MainWindow", "Ruggedness"))
        self.upload_3.setText(_translate("MainWindow", "Upload"))
        self.label_8.setText(_translate("MainWindow", "BT36H"))
        self.upload_8.setText(_translate("MainWindow", "Upload"))
        self.submitbtn.setText(_translate("MainWindow", "Submit"))
        self.clearbtn.setText(_translate("MainWindow", "Clear"))
        self.label_11.setText(_translate("MainWindow", "AMSR Input Files"))
import Images_rc
